meta_product_name: "Med-IA"
meta_title: "Med-IA - Product tagline"
meta_description: "Diagnostics plus rapides et plus précis avec l'assistant Med-IA!"
meta_image: "logo-nobg-media.png" # should exist in `app/assets/images/`
